apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  namespace: health
spec:
  containers:
  - name: memory-demo-ctr
    image: ravihari/stress-ng
    resources:
      limits:
        memory: "100Mi"
      requests:
        memory: "100Mi"
    command: ["/usr/bin/stress-ng"]
    args: ["--vm", "1", "--vm-bytes", "98M", "--vm-hang", "1", "-b", "60000"]
