apiVersion: v1
kind: ServiceAccount
metadata:
  name: activemonitor-controller-sa
  namespace: health
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: activemonitor-controller-role
  namespace: health
rules:
- apiGroups: [""]
  resources: [pods, services, configmaps, secrets, serviceaccounts, events]
  verbs: [get, list, watch, create, update, patch, delete]
- apiGroups: ["apps"]
  resources: [deployments, replicasets]
  verbs: [get, list, watch, create, update, patch, delete]
- apiGroups: ["argoproj.io"]
  resources: [workflows, workflowtasksets]
  verbs: [get, list, watch, create, update, patch, delete]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: [roles, rolebindings]
  verbs: [get, list, watch, create, update, patch, delete]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: activemonitor-controller-clusterrole
rules:
- apiGroups: ["activemonitor.keikoproj.io"]
  resources: [healthchecks, healthchecks/status]
  verbs: [get, list, watch, create, update, patch, delete]
- apiGroups: ["argoproj.io"]
  resources: [workflows]
  verbs: [get, list, watch, create, update, patch, delete]
- apiGroups: [""]
  resources: [pods, events, serviceaccounts]
  verbs: [get, list, watch, create, update, patch, delete]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: [clusterroles, clusterrolebindings]
  verbs: [get, list, watch, create, update, patch, delete]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: activemonitor-controller-rb
  namespace: health
subjects:
- kind: ServiceAccount
  name: activemonitor-controller-sa
  namespace: health
roleRef:
  kind: Role
  name: activemonitor-controller-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: activemonitor-controller-cluster-rb
subjects:
- kind: ServiceAccount
  name: activemonitor-controller-sa
  namespace: health
roleRef:
  kind: ClusterRole
  name: activemonitor-controller-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemonitor-controller
  namespace: health
spec:
  replicas: 1
  selector:
    matchLabels:
      name: activemonitor-controller
  template:
    metadata:
      labels:
        name: activemonitor-controller
    spec:
      containers:
        - name: active-monitor
          image: keikoproj/active-monitor:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "50m"
              memory: "80Mi"
      serviceAccountName: activemonitor-controller-sa
