apiVersion: activemonitor.keikoproj.io/v1alpha1
kind: HealthCheck
metadata:
  name: inline-hello-pause
  generateName: inline-hello-
  namespace: health
spec:
  repeatAfterSec: 0 # duration in seconds
  #  schedule:
  #    cron: "@every 1m"
  level: cluster
  workflow:
    generateName: inline-hello-
    resource:
      namespace: health # workflow will be submitted in this ns
      serviceAccount: activemonitor-controller-sa # workflow will be submitted using this acct
      source:
        inline: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            labels:
              workflows.argoproj.io/controller-instanceid: activemonitor-workflows
            generateName: hello-world-
          spec:
            entrypoint: whalesay
            templates:
              -
                container:
                  args:
                    - "hello world"
                  command:
                    - cowsay
                  image: "docker/whalesay:latest"
                name: whalesay
