apiVersion: activemonitor.keikoproj.io/v1alpha1
kind: HealthCheck
metadata:
  generateName: inline-hello-
  namespace: test
spec:
  repeatAfterSec: 60 # duration in seconds
  level: namespace
  workflow:
    generateName: inline-hello-
    resource:
      namespace: test # workflow will be submitted in this ns
      serviceAccount: testnssa
      source:
        inline: |
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              labels:
                workflows.argoproj.io/controller-instanceid: activemonitor-workflows
              generateName: hello-world-
            spec:
              entrypoint: whalesay
              templates:
                -
                  container:
                    args:
                      - "hello world"
                    command:
                      - cowsay
                    image: "docker/whalesay:latest"
                  name: whalesay
