apiVersion: activemonitor.keikoproj.io.my.domain/v1alpha1
kind: HealthCheck
metadata:
  labels:
    app.kubernetes.io/name: healthcheck
    app.kubernetes.io/instance: healthcheck-sample
    app.kubernetes.io/part-of: jnk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: jnk
  name: healthcheck-sample
spec:
  # TODO(user): Add fields here
